name: events_emitter2
description: Type-safe, multi-listenable, dispose safe event handling classes
version: 1.0.4
repository: https://github.com/moham96/events_emitter2

environment:
  sdk: ^3.1.3

dependencies:
  synchronized: ^3.1.0
  meta: ">=1.9.0"
  logging: ^1.2.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
